### ISSUE TITLE
We need to model/create our Item entity

### ISSUE THREAD

**Issue by bephrimast** [NullTraining/project-team2#17]
In order to be able to submit LOST or FOUND items and store them in the database
For users
We will add an Item entity

It should/could have the following fields:

```    name
    location
    category (Taxonomy entity required?)
    picture
    weight
    found
    user
```

**Comment by zgperak** [comment]
Should location be JSON field type in MySql or should we use another database for this

**Comment by zgperak** [comment]
Will picture be Picture object or, I mean how detailed will we go into DDD
same question for weight
what is "found" for? user who found it or ...?

so much questions ... lol

**Comment by 8eph** [comment]
Some more detail on the proposed model:

Item
One to one -> Location
Many to one -> Category
Link to uploaded asset -> Picture
DateTime -> Found date
Many to one -> User

**Comment by 8eph** [comment]
MySQL should be just fine IMO for this project, we're not looking at millions of concurrent users just yet. ;)

https://www.percona.com/blog/2013/10/21/using-the-new-mysql-spatial-functions-5-6-for-geo-enabled-applications/

**Comment by bephrimast** [comment]
Closing this as too broad.

The Item entity exists as of  #75
