### ISSUE TITLE
Add Location entity

### ISSUE THREAD

**Issue by bephrimast** [NullTraining/project-team2#82]
Each Item will have a OneToOne relation to Location

Proposed model for location:

id
street
streetNumber
postBox
city - text field (TBD)
county (optional) - text field (TBD)
country (optional) - text field (TBD)
Points (oneToMany)

Normally, a Location will have a single Point (representing only Latitude and Longitude of GPS coordinates) if it is a 'Pin', but by adding multiple we can create overlays representing an area or path.

**Comment by zgperak** [comment]
Looks ok for starters

**Comment by bephrimast** [comment]
Omitting County, and Country, we'll add it when we need it.
