### ISSUE TITLE
Items must have users

### ISSUE THREAD

**Issue by zgperak** [NullTraining/project-team2#97]
In order to know which user found/lost item
Item entity must be related to user.

**Comment by bephrimast** [comment]
Users should have the ability to submit items when they are not logged in or registered.

The way I've seen this is done usually is to defer the registration to the last step and associate an now-existing Item/Location to the newly created user upon activation.

Ideally, this could be a one-click 'Login with Facebook/Google', or a simple 'email/password/repeat password -> activate email' form.
